development:
  adapter: postgresql
  encoding: unicode
  database: butchershop_development
  pool: 5
  username: mkim
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: butchershop_test
  pool: 5
  username: mkim
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: butchershop_production
  pool: 5
  username: deploy
  password:
